name: tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: check-style
        - linux: build-dist
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: test-xdist
          python-version: 3.9
        - linux: test-xdist
          python-version: 3.10
        - linux: test-xdist
          python-version: 3.11
        - macos: test-xdist
          python-version: 3.11
        - linux: test-cov-xdist
          coverage: codecov
          pytest-results-summary: true
