name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: ${{ matrix.toxenv }} (Python ${{ matrix.python }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toxenv: [ test-xdist ]
        python: [ '3.9', '3.10', '3.11', '3.12-dev' ]
        os: [ ubuntu-latest, macos-latest ]
        include:
          - toxenv: check-style
            os: ubuntu-latest
            python: '3.11'
          - toxenv: build-dist
            os: ubuntu-latest
            python: '3.11'
          - toxenv: test-cov-xdist
            os: ubuntu-latest
            python: '3.11'
    continue-on-error: ${{ matrix.python == '3.12-dev' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - run: pip install tox
      - run: tox -e ${{ matrix.toxenv }}
      - uses: codecov/codecov-action@v3
        if: contains(matrix.toxenv, '-cov')
        with:
          file: ./coverage.xml
          flags: unit
          fail_ci_if_error: true
