name: tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: py39-parallel
        - linux: py310-parallel
        - linux: py311-parallel
        - linux: py3-parallel
        - macos: py3-parallel
        - linux: py3-cov-parallel
          coverage: codecov
          pytest-results-summary: true
