name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toxenv: [ check-style, check-build ]
        python: [ '3.11' ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - run: pip install tox
      - uses: actions/checkout@v3
      - run: tox -e ${{ matrix.toxenv }}
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        toxenv: [ test-xdist ]
        python: [ '3.8', '3.9', '3.10', '3.11', '3.12-dev' ]
        os: [ ubuntu-latest, macos-latest ]
        include:
          - toxenv: test-cov-xdist
            os: ubuntu-latest
            python: '3.11'
    continue-on-error: ${{ matrix.python == '3.12-dev' }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - run: pip install tox
      - uses: actions/checkout@v3
      - run: tox -e ${{ matrix.toxenv }}
      - uses: codecov/codecov-action@v3
        if: contains(matrix.toxenv, '-cov')
        with:
          file: ./coverage.xml
          flags: unit
          fail_ci_if_error: true
