name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - run: pip install ruff
      - run: ruff .
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [ 'pypy-3.7', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12-dev' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    continue-on-error: ${{ matrix.python-version == '3.12-dev' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - run: pip install ".[test]" pytest-xdist pytest-cov
      - run: pytest -n auto --cov=. --cov-config=pyproject.toml --cov-report=term-missing --cov-report=xml
      - uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.10'
        with:
          file: ./coverage.xml
          flags: unit
          fail_ci_if_error: true
